Repository CalebCyphers/Whats-Cookin, pull requests merged in 2020-09, with the labels that each got.

#59 User functionality ng
  src/user.js
  test/user-test.js
Labels: documentation

#60 Make small dataset for recipeData to be used in unit tests
  test/user-test.js
Labels: documentation

#61 Recipe refactor tj
  src/recipe.js
  test/recipe-test.js
Labels: Recipe Class, Recipe TDD

#63 Static structure ng
  src/images/hamburger-icon.png
  src/images/heart-icon.png
  src/images/plus-icon.png
  src/images/search-icon.png
  src/images/x-icon.png
  src/index.html
  src/pantry.html
  src/styles.css
Labels: accessibility, documentation

#79 Recipe popup ng
  dist/index.html
  dist/main.bundle.js
  src/domUpdates.js
  src/index.html
  src/recipe.js
  src/scripts.js
  test/domUpdates-test.js
Labels: documentation

#83 Read me ng
  README.md
Labels: documentation

#85 Spies round2 ng
  test/domUpdates-test.js
  test/recipe-test.js
Labels: documentation
